github: [sanot-tech]
patreon: # YOUR_PATREON
open_collective: # YOUR_ORG
ko_fi: # YOUR_KO_FI
tidelift: # YOUR_TIDELIFT
community_bridge: # YOUR_BRIDGE
liberapay: # YOUR_LIBERAPAY
issuehunt: # YOUR_ISSUEHUNT
otechie: # YOUR_OTECHIE
custom: # Custom links
  - https://github.com/sanot-tech/RadioFlow
